### ISSUE TITLE
Windows下字符串拼接问题

### ISSUE THREAD

**Issue by jqknono** [JYbill/picgo-plugin-cloudflare-r2#1]
![image](https://github.com/user-attachments/assets/e26b9828-5f4f-4f19-881e-a560254f7ee3)

resolve函数会返回本地绝对路径, 导致用路径会显示为 https://image.example.dev/C%3A%5CWINDOWS%5Csystem32%5Cblog%5C20241105104145.png

**Comment by JYbill** [comment]
我手里没有window电脑，改path.resolve()为path.join()了

**Comment by jqknono** [comment]
@JYbill path.join也无法避免`\`被转为`%5C`的问题, 我试过了, 只有手动拼接支持windows下上传路径正常显示.

**Comment by JYbill** [comment]
想请问一下，你这边的情况是
```ts
let uri = join(storageKey, filename) // <- 这里filename拿到的是一个路径吗？
```
[https://github.com/JYbill/picgo-plugin-cloudflare-r2/blob/35e907f78d1130c00bdec0e8b6d1a361e6bf9d9c/src/index.ts#L79](code)

**Comment by JYbill** [comment]
> 想请问一下，你这边的情况是
> 
> ```ts
> let uri = join(storageKey, filename) // <- 这里filename拿到的是一个路径吗？
> ```
> 
> [https://github.com/JYbill/picgo-plugin-cloudflare-r2/blob/35e907f78d1130c00bdec0e8b6d1a361e6bf9d9c/src/index.ts#L79](code)

按道理picgo这里从
```ts
          const { fileName: filename, buffer, base64Image, extname, imgUrl } = imageItem
```
这里解出来的filename应该为路径下的文件名才对呀

**Comment by jqknono** [comment]
@JYbill windows下解出来的确是正确路径名, 但是windows下的路径是反斜杠`\`, 不是linux和mac下的`/`, 不能直接作为key填入

![image](https://github.com/user-attachments/assets/4805e755-143e-4bca-8aad-00053751f061)

**Comment by jqknono** [comment]
@JYbill key中的`\`会被转换为%5C, 如果要使用join, 至少要在填objRes的key时替换`\`为`/`. 但这里实际上不需要文件路径, 所以没有必要引用path, 意图是获取一个key和一个url, 直接拼就可以, key和url是明确的使用`/`分割路径.
此外多余的`/`会在cloudflare中生成不必要的路径, 参考这个改法, 连着的`//`替换成`/`, 可以增加一些输入容错.

https://github.com/JYbill/picgo-plugin-cloudflare-r2/pull/2/files

**Comment by JYbill** [comment]
我搞了台win，明白什么问题了，win/mac path模块不一致性导致的，这个问题你这个方法也可以修复，为了保证不出bug，我这里还是以nodejs官方api来保证path的一致性
```ts
join("/////md/////", "////1.png") // 这里我就是为了懒得去replace("//", "")才用的
// get /md/1.png
```

**Comment by JYbill** [comment]
没有问题我就Close掉的Issue的
